{
	"version": 1734957296,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/particles.png",
		"images/purplecircleoutlinepng-sheet0.png",
		"images/wtfcoin-sheet0.png",
		"images/wtfcoin-sheet1.png",
		"images/wtfcoin-sheet2.png",
		"images/wtfcoin-sheet3.png",
		"images/wtfcoin-sheet4.png",
		"images/wtfcoin-sheet5.png",
		"images/wtfcoin-sheet6.png",
		"images/wtfcoin-sheet7.png",
		"images/wtfcoin-sheet8.png",
		"images/wtfcoin-sheet9.png",
		"images/wtfcoin-sheet10.png",
		"images/wtfcoin-sheet11.png",
		"images/wtfcoin-sheet12.png",
		"images/wtfcoin-sheet13.png",
		"images/wtfcoin-sheet14.png",
		"images/wtfcoin-sheet15.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/feel lucky bgm.m4a",
		"media/feel lucky bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}